
package vista;

import Control.ControlBD;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ANIBAL
 */
public class DatosHotel extends javax.swing.JPanel {

    ControlBD  enlace  = new ControlBD();
    Connection conect = enlace.conectar();
    public DatosHotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        txthabitaciones = new javax.swing.JTextField();
        txtadmi = new javax.swing.JTextField();
        txtAforo = new javax.swing.JTextField();
        txtdirec = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ciudad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 153));
        setPreferredSize(new java.awt.Dimension(920, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 160, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("DATOS DEL HOTEL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel4.setText("NUMERO DE HABITACIONES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel2.setText("DIRECCION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel3.setText("CODIGO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 158, 50, 20));

        jLabel5.setText("RUC");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jLabel6.setText("CIUDAD");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));
        jPanel1.add(txtruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 170, 40));
        jPanel1.add(txthabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 170, -1));

        txtadmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadmiActionPerformed(evt);
            }
        });
        jPanel1.add(txtadmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 170, -1));
        jPanel1.add(txtAforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 50, -1));
        jPanel1.add(txtdirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 310, 40));

        jLabel7.setText("ADMINISTRADOR");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        ciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIMA", "CUZCO", "AREQUIPA" }));
        jPanel1.add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 170, -1));

        jLabel8.setText("AFORO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 50, -1));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 50, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void txtadmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadmiActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
// Obtener la ciudad seleccionada del JComboBox
    String ciudadSeleccionada = ciudad.getSelectedItem().toString();
    
    // Consulta SQL para obtener la información del hotel según la ciudad seleccionada
    String sql = "SELECT CodigoHotel,Ruc, DireccionHotel, Nombre, Apellido, CantidadHabitaciones, Aforo "
               + "FROM hotel h "
               + "JOIN administrador a ON h.CodigoAdministrador = a.CodigoAdministrador "
               + "WHERE h.Ciudad = ?";
    
    try {
        PreparedStatement pst = (PreparedStatement)conect.prepareStatement(sql);
        pst.setString(1, ciudadSeleccionada);
        ResultSet rs = (ResultSet) pst.executeQuery();
        
        if (rs.next()) {
            // Rellenar los JTextField con la información recuperada
            txtruc.setText(rs.getString("Ruc"));
            txtdirec.setText(rs.getString("DireccionHotel"));
            txtadmi.setText(rs.getString("Nombre") + " " + rs.getString("Apellido"));
            txthabitaciones.setText(String.valueOf(rs.getInt("CantidadHabitaciones")));
            txtAforo.setText(String.valueOf(rs.getInt("Aforo")));
            txtCodigo.setText(String.valueOf(rs.getInt("CodigoHotel")));
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró información para la ciudad seleccionada.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al recuperar la información: " + e.toString());
    }
    }//GEN-LAST:event_btnMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> ciudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAforo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtadmi;
    private javax.swing.JTextField txtdirec;
    private javax.swing.JTextField txthabitaciones;
    private javax.swing.JTextField txtruc;
    // End of variables declaration//GEN-END:variables
}
